config/routes.rb
Rails.application.routes.draw do
  resources :course_kelases, only: [:index,:show] do
    resources :assignments
  end

  resources :projects
  resources :courses
  resources :kelases
  devise_for :users
  root 'kelases#index'
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :course_kelas
  has_many :projects
  after_create :setup_project

  private
    def setup_project
      self.course_kelas.kelas.students.each do |student|
        student.projects.create!(name: self.name, assignment_id: self.id)
      end
    end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :set_assignment, only: [:show, :edit, :update, :destroy]
  before_action :set_course_kelas, only: [:new, :create, :show]
  # GET /assignments
  # GET /assignments.json
  def index
    @assignments = Assignment.all
  end

  # GET /assignments/1
  # GET /assignments/1.json
  def show
  end

  # GET /assignments/new
  def new
    @assignment = @course_kelas.assignments.build
  end

  # GET /assignments/1/edit
  def edit
  end

  # POST /assignments
  # POST /assignments.json
  def create
    @assignment = @course_kelas.assignments.build(assignment_params)

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to course_kelas_assignment_path(@course_kelas, @assignment), notice: 'Assignment was successfully created.' }
        format.json { render :show, status: :created, location: @assignment }
      else
        format.html { render :new }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assignments/1
  # PATCH/PUT /assignments/1.json
  def update
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to @assignment, notice: 'Assignment was successfully updated.' }
        format.json { render :show, status: :ok, location: @assignment }
      else
        format.html { render :edit }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1
  # DELETE /assignments/1.json
  def destroy
    @assignment.destroy
    respond_to do |format|
      format.html { redirect_to assignments_url, notice: 'Assignment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_course_kelas
      @course_kelas = CourseKelas.find(params[:course_kelas_id])
    end

    def set_assignment
      @assignment = Assignment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assignment_params
      params.require(:assignment).permit(:name, :course_kelas_id)
    end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_form.html.erb
<%= simple_form_for @assignment, url: course_kelas_assignments_path(@course_kelas) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.association :course_kelas %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/assignments/edit.html.erb
<h1>Editing Assignment</h1>

<%= render 'form' %>

<%= link_to 'Show', @assignment %> |
<%= link_to 'Back', assignments_path %>

app/views/assignments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Assignments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Course kelas</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assignments.each do |assignment| %>
      <tr>
        <td><%= assignment.name %></td>
        <td><%= assignment.course_kelas %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assignment', '#' %>

app/views/assignments/new.html.erb
<h1>New Assignment</h1>

<%= render 'form' %>

<%= link_to 'Back', course_kelas_assignments_path %>

app/views/assignments/show.html.slim
p#notice
  = notice
p
  strong
    | Name:
  = @assignment.name
p
  strong
    | Course kelas:
  = @assignment.course_kelas.course.name
- if @assignment.projects.any?
  table.table
    thead
      tr
        th
          | Student
        th 
          | Projects
        th 
          | Projects Status
        th 
          | Test Status
        th 
          | Total File
        th 
          | Total Commit
        th 
          | Total Branch
        th 
          | Similarity Score
        th[colspan="3"]
    tbody
      - @assignment.projects.each do |project|
        tr
          td
            = project.user.email
          td 
            = link_to project.name, project
          td 
            | unfinished
          td 
            | Success
          td 
            | 100
          td
            | 10
          td 
            | 3
          td 
            | 5%

= link_to 'Edit', edit_course_kelas_assignment_path(@course_kelas, @assignment)
|  |
= link_to 'Back', course_kelas_path(@course_kelas)