config/routes.rb
Rails.application.routes.draw do
  resources :course_kelases, only: [:index,:show] do
    resources :assignments
  end

  resources :projects
  resources :courses
  resources :kelases
  devise_for :users
  root 'kelases#index'
end

app/controllers/course_kelases_controller.rb
class CourseKelasesController < ApplicationController
  def show
    @course_kelas = CourseKelas.find(params[:id])
  end

  def index
    @course_kelases = current_user.course_kelases
  end

  def create_assignment
  end
end

app/helpers/course_kelases_helper.rb
module CourseKelasesHelper
end

app/views/course_kelases/create_assignment.html.erb
<h1>CourseKelases#create_assignment</h1>
<p>Find me in app/views/course_kelases/create_assignment.html.erb</p>

app/views/course_kelases/index.html.slim
p#notice
  = notice
h1
  | My Classes
table.table
  thead
    tr
      th
        | Name
      th 
        | Teacher
      th 
        | Kelas
      th[colspan="3"]
  tbody
    - @course_kelases.each do |course_kelas|
      tr
        td
          = link_to course_kelas.course.name, course_kelas.course
        td 
          = course_kelas.teacher.email
        td 
          = link_to course_kelas.kelas.name, course_kelas.kelas
        td
          = link_to 'Go To Class', course_kelas
        / td
        /   = link_to 'Edit', edit_course_path(course)
        / td
        /   = link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }

app/views/course_kelases/show.html.slim
p#notice
  = notice
p
  strong
    | Name:
  = @course_kelas.course.name
p
  strong
    | Teacher:
  = @course_kelas.teacher.email
p 
  strong
    | Class:
  = @course_kelas.kelas.name
= link_to 'create assignment', new_course_kelas_assignment_path(@course_kelas)
p
  strong
  - if @course_kelas.assignments.any?
    table.table
      thead
        tr
          th
            | Assignments
          th[colspan="3"]
      tbody
        - @course_kelas.assignments.each do |assignment|
          tr
            td
              = link_to assignment.name, course_kelas_assignment_path(@course_kelas,assignment)
p
  strong
  - if @course_kelas.kelas.students.any?
    table.table
      thead
        tr
          th
            | Students
          th[colspan="3"]
      tbody
        - @course_kelas.kelas.students.each do |student|
          tr
            td
              = student.email
p 
  strong
  - if @course_kelas.projects.any?
    table.table
      thead
        tr
          th
            | Projects
          th[colspan="3"]
      tbody
        - @course_kelas.projects.each do |project|
          tr
            td
              = link_to project.name, project 