config/routes.rb
Rails.application.routes.draw do
  resources :course_kelases, only: [:index,:show] do
    resources :assignments
  end

  resources :projects
  resources :courses
  resources :kelases
  devise_for :users
  root 'kelases#index'
end

app/views/layouts/_header.html.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed data-toggle="collapse" data-target="#buncis" type="button" 
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      .navbar-brand =link_to root_path
        span.glyphicon.glyphicon-heart.pink
    .collapse.navbar-collapse id="buncis"
      ul.nav.navbar-nav.navbar-left
        li 
          = link_to 'courses', courses_path
        li
          = link_to 'classes', kelases_path
        li 
          = link_to 'projects', projects_path
        li 
          = link_to 'students', '#'
        li 
          = link_to 'teachers', '#'
        li 
          = link_to 'my class', course_kelases_path
      ul.nav.navbar-nav.navbar-right
        -if user_signed_in?
          li
            = link_to current_user.email, edit_user_registration_path
          li
            = link_to 'sign out', destroy_user_session_path, method: :delete
        -else
          li
            = link_to 'sign in', new_user_session_path

app/views/layouts/_teachers_toolbar.html.slim
= link_to 'create assignment', '#'

app/views/layouts/application.html.slim
doctype html
html
  head
    title Gitku
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render 'layouts/header'
    .container
      = yield